openapi: 3.0.1
info:
  version: 1.0.0
  title: GCIS REST API Wrapper
  license:
    name: BSD 3-Clause
    url: 'https://github.com/minchao/gcis-rest/blob/master/LICENSE'
paths:
  /companies:
    get:
      summary: Finds companies by keyword
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum:
              - '01' # 核准設立
              - '02' # 核准設立，但已命令解散
              - '03' # 重整
              - '04' # 解散
              - '05' # 撤銷
              - '06' # 破產
              - '07' # 合併解散
              - '08' # 撤回認許
              - '09' # 廢止
              - '10' # 廢止認許
              - '11' # 解散已清算完結
              - '12' # 撤銷已清算完結
              - '13' # 廢止已清算完結
              - '14' # 撤回認許已清算完結
              - '15' # 撤銷認許已清算完結
              - '16' # 廢止認許已清算完結
              - '17' # 撤銷認許
              - '18' # 分割解散
              - '19' # 終止破產
              - '20' # 中止破產
              - '21' # 塗銷破產
              - '22' # 破產程序終結(終止)
              - '23' # 破產程序終結(終止)清算中
              - '24' # 破產已清算完結
              - '25' # 接管
              - '26' # 撤銷無需清算
              - '27' # 撤銷許可
              - '28' # 廢止許可
              - '29' # 撤銷許可已清算完結
              - '30' # 廢止許可已清算完結
              - '31' # 清理
              - '32' # 撤銷公司設立
              - '33' # 清理完結
            default: '01'
        - name: limit
          in: query
          schema:
            type: integer
        - name: offset
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Companies'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /companies/{id}:
    get:
      summary: Find company by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '404':
          description: Company not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Company:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Companies:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/Company'
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
