AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GCIS REST API wrapper.

Parameters:

  ParamGCISBaseURL:
    Type: String
    Default: ""
    AllowedValues:
      - ""
      - "http://data.gcis.nat.gov.tw/"
      - "https://data.gcis.nat.gov.tw/"

Globals:

  Function:
    Runtime: go1.x
    MemorySize: 128
    Timeout: 10
    Environment:
      Variables:
        GCIS_BASE_URL: !Ref ParamGCISBaseURL

Resources:

  CompaniesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: company
      Events:
        ProxyCompanies:
          Type: Api
          Properties:
            Path: /companies
            Method: GET
        ProxyCompaniesGreedy:
          Type: Api
          Properties:
            Path: /companies/{id}
            Method: GET

Outputs:

  GcisRestApi:
    Description: "API Gateway endpoint URL for Prod environment for GCIS REST API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: GcisRestApi
